
//written by Sophia Kobzar
//CS 3345
//HomeworkTest has Try and Catch blocks which makes it look like there are no errors in the test
//to find the errors instead of looking at the Failure trace box 
//you need to read the output Console to find errors and passes in the tests
import junit.framework.TestCase;
public class NexMedMainTest extends TestCase 
{
		// this test passes because expected value equals the product of x and y
	public void test_NexMed()
	{
		
	}
}